### ISSUE TITLE
new#3

### ISSUE THREAD

**Issue by pablanopete** [pablanopete/TestRepo-SOB#11]
issue

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im:444/img/deploying_contract.png)
Transaction: [0xe1cf36ac9ae42c36be9f1159756ce892eab5489ea9913809ceb1c72f2be8d7d4](https://ropsten.etherscan.io/tx/0xe1cf36ac9ae42c36be9f1159756ce892eab5489ea9913809ceb1c72f2be8d7d4)
